const PRESIDENTS = [
  { n:1, name:"George Washington", short:"Washington", mnemonic:"GEORGE washing a giant TON of laundry — door 1.", emoji:"🧺" },
  { n:2, name:"John Adams", short:"Adams", mnemonic:"JOHN adding big numbers — door 2.", emoji:"➕" },
  { n:3, name:"Thomas Jefferson", short:"Jefferson", mnemonic:"THOMAS the chef’s son cooking atoms — door 3.", emoji:"👨‍🍳" },
  { n:4, name:"James Madison", short:"Madison", mnemonic:"JAMES and a MAD sun on the grill — door 4.", emoji:"☀️" },
  { n:5, name:"James Monroe", short:"Monroe", mnemonic:"JAMES the man ROWing with a 5 on the oar.", emoji:"🚣" },
  { n:6, name:"John Quincy Adams", short:"Q. Adams", mnemonic:"JOHN Q’s cue ball bouncing into a dam — door 6.", emoji:"🎱" },
  { n:7, name:"Andrew Jackson", short:"Jackson", mnemonic:"ANDREW the jack-in-the-box popping from a pumpkin — door 7.", emoji:"🎃" },
  { n:8, name:"Martin Van Buren", short:"Van Buren", mnemonic:"MARTIN’s VAN BURNing in the freezer — door 8.", emoji:"🚐" },
  { n:9, name:"William Henry Harrison", short:"W.H. Harrison", mnemonic:"WILL the hairy monkey — door 9.", emoji:"🐒" },
  { n:10, name:"John Tyler", short:"Tyler", mnemonic:"JOHN tying TEN knots.", emoji:"🧶" },
  { n:11, name:"James K. Polk", short:"Polk", mnemonic:"JAMES poking holes that look like 11.", emoji:"🥢" },
  { n:12, name:"Zachary Taylor", short:"Taylor", mnemonic:"ZACH the tailor sewing 12 buttons.", emoji:"🧵" },
  { n:13, name:"Millard Fillmore", short:"Fillmore", mnemonic:"MILLARD filling MORE glasses — 13 cups.", emoji:"🥛" },
  { n:14, name:"Franklin Pierce", short:"Pierce", mnemonic:"FRANKLIN’s spear PIERCING 14.", emoji:"🗡️" },
  { n:15, name:"James Buchanan", short:"Buchanan", mnemonic:"JAMES firing 15 cannons that say BOO.", emoji:"💣" },
  { n:16, name:"Abraham Lincoln", short:"Lincoln", mnemonic:"ABE in a tall hat with 16 stars.", emoji:"🎩" },
  { n:17, name:"Andrew Johnson", short:"A. Johnson", mnemonic:"ANDREW, John’s son, stitching a bed with 17 pillows.", emoji:"🧵" },
  { n:18, name:"Ulysses S. Grant", short:"Grant", mnemonic:"ULYSSES the genie GRANTing wishes — door 18.", emoji:"🧞" },
  { n:19, name:"Rutherford B. Hayes", short:"Hayes", mnemonic:"RUTHERFORD saying HEY with a high-five in the hay — door 19.", emoji:"🙌" },
  { n:20, name:"James A. Garfield", short:"Garfield", mnemonic:"JAMES Garfield the cat eating 20 lasagnas.", emoji:"🐱" },
  { n:21, name:"Chester A. Arthur", short:"Arthur", mnemonic:"CHEESE-ter King Arthur signing 21 books as an AUTHOR.", emoji:"🧀" },
  { n:22, name:"Grover Cleveland", short:"Cleveland", mnemonic:"GROVER’s CLEAVER cutting corn — door 22.", emoji:"🌽" },
  { n:23, name:"Benjamin Harrison", short:"B. Harrison", mnemonic:"A HAIRY monkey counting 23 Benjamin $100 bills!", emoji:"🦍" },
  { n:24, name:"Grover Cleveland", short:"Cleveland 2", mnemonic:"GROVER’s cleaver comes back for round two — door 24.", emoji:"🌽" },
  { n:25, name:"William McKinley", short:"McKinley", mnemonic:"McDonald the KING at the KINLEY gate with 25 burgers.", emoji:"🍔" },
  { n:26, name:"Theodore Roosevelt", short:"T. Roosevelt", mnemonic:"Teddy on a horse wearing a belt of 26 ROSES.", emoji:"🌹" },
  { n:27, name:"William Howard Taft", short:"Taft", mnemonic:"WILL stuck in sticky TAFFY shaped like 27.", emoji:"🍬" },
  { n:28, name:"Woodrow Wilson", short:"Wilson", mnemonic:"WOODROW’s will floating out like a ghost — door 28.", emoji:"📜" },
  { n:29, name:"Warren G. Harding", short:"Harding", mnemonic:"WARREN the HARD metal man — door 29.", emoji:"🤖" },
  { n:30, name:"Calvin Coolidge", short:"Coolidge", mnemonic:"CALVIN standing in a COOLER — door 30.", emoji:"🧊" },
  { n:31, name:"Herbert Hoover", short:"Hoover", mnemonic:"HERBERT’s vacuum HOOVERing — door 31.", emoji:"🧹" },
  { n:32, name:"Franklin D. Roosevelt", short:"FDR", mnemonic:"FRANKLIN’s ROOSTER with roses — door 32.", emoji:"🐓" },
  { n:33, name:"Harry S. Truman", short:"Truman", mnemonic:"HARRY the TRUE man with a star — door 33.", emoji:"⭐" },
  { n:34, name:"Dwight D. Eisenhower", short:"Eisenhower", mnemonic:"DWIGHT’s EYEball watching — door 34.", emoji:"👁️" },
  { n:35, name:"John F. Kennedy", short:"Kennedy", mnemonic:"JOHN the Ken doll with candy — door 35.", emoji:"🍬" },
  { n:36, name:"Lyndon B. Johnson", short:"L.B. Johnson", mnemonic:"LYNDON, John’s son, in the LBJ hat — door 36.", emoji:"🧢" },
  { n:37, name:"Richard Nixon", short:"Nixon", mnemonic:"RICHARD mixing NIX-on soup — door 37.", emoji:"🥣" },
  { n:38, name:"Gerald Ford", short:"Ford", mnemonic:"GERALD driving a FORD — door 38.", emoji:"🚗" },
  { n:39, name:"Jimmy Carter", short:"Carter", mnemonic:"JIMMY’s CART of peanuts — door 39.", emoji:"🥜" },
  { n:40, name:"Ronald Reagan", short:"Reagan", mnemonic:"RONALD’s ray-gun shooting stars — door 40.", emoji:"🔫" },
  { n:41, name:"George H. W. Bush", short:"H.W. Bush", mnemonic:"GEORGE by the H.W. bush — door 41.", emoji:"🌳" },
  { n:42, name:"Bill Clinton", short:"Clinton", mnemonic:"BILL the dollar climbing — door 42.", emoji:"💵" },
  { n:43, name:"George W. Bush", short:"W. Bush", mnemonic:"GEORGE by the W bush — door 43.", emoji:"🌲" },
  { n:44, name:"Barack Obama", short:"Obama", mnemonic:"BARACK and a bar of soap with an O — door 44.", emoji:"🧼" },
  { n:45, name:"Donald Trump", short:"Trump (1st)", mnemonic:"DONALD’s golden trumpet — door 45.", emoji:"🎺" },
  { n:46, name:"Joe Biden", short:"Biden", mnemonic:"JOE on a bicycle with a 46 flag.", emoji:"🚲" },
  { n:47, name:"Donald Trump", short:"Trump (2nd)", mnemonic:"DONALD’s trumpet encore — door 47.", emoji:"🎺" }
];
