const PRESIDENTS = [
  { n:1, name:"George Washington", short:"Washington", mnemonic:"Washing a giant TON of laundry! Splash!", emoji:"🧺" },
  { n:2, name:"John Adams", short:"Adams", mnemonic:"Adding big numbers on a chalkboard that keeps growing.", emoji:"➕" },
  { n:3, name:"Thomas Jefferson", short:"Jefferson", mnemonic:"A chef’s son (Jeff-er-son) cooking atoms in a frying pan.", emoji:"👨‍🍳" },
  { n:4, name:"James Madison", short:"Madison", mnemonic:"A MAD sun yelling under a grill!", emoji:"☀️" },
  { n:5, name:"James Monroe", short:"Monroe", mnemonic:"A man ROWing a boat with a big number 5.", emoji:"🚣" },
  { n:6, name:"John Quincy Adams", short:"Q. Adams", mnemonic:"A cue ball bouncing into a dam (Q + Adams).", emoji:"🎱" },
  { n:7, name:"Andrew Jackson", short:"Jackson", mnemonic:"A jack-in-the-box popping out of a Jack-o-lantern!", emoji:"🎃" },
  { n:8, name:"Martin Van Buren", short:"Van Buren", mnemonic:"A VAN that is BURNing (burrrr!) in the freezer.", emoji:"🚐" },
  { n:9, name:"William Henry Harrison", short:"W.H. Harrison", mnemonic:"A hairy monkey with lots of HAIR!", emoji:"🐒" },
  { n:10, name:"John Tyler", short:"Tyler", mnemonic:"Tying TEN knots in a long rope.", emoji:"🪢" },
  { n:11, name:"James K. Polk", short:"Polk", mnemonic:"Poking holes in the yard with two sticks (looks like 11).", emoji:"🥢" },
  { n:12, name:"Zachary Taylor", short:"Taylor", mnemonic:"A tailor sewing twelve shiny buttons.", emoji:"🧵" },
  { n:13, name:"Millard Fillmore", short:"Fillmore", mnemonic:"Filling MORE and more glasses of water (13 cups!).", emoji:"🥛" },
  { n:14, name:"Franklin Pierce", short:"Pierce", mnemonic:"A spear PIERCING through the number 14.", emoji:"🗡️" },
  { n:15, name:"James Buchanan", short:"Buchanan", mnemonic:"Firing fifteen cannons that say BOO!", emoji:"💣" },
  { n:16, name:"Abraham Lincoln", short:"Lincoln", mnemonic:"Lincoln in a tall top hat giving a speech with 16 stars.", emoji:"🎩" },
  { n:17, name:"Andrew Johnson", short:"A. Johnson", mnemonic:"A giant sewing needle (Johnson) stitching a bed.", emoji:"🪡" },
  { n:18, name:"Ulysses S. Grant", short:"Grant", mnemonic:"A friendly genie GRANTing wishes.", emoji:"🧞" },
  { n:19, name:"Rutherford B. Hayes", short:"Hayes", mnemonic:"Saying HEY! while giving a high-five in a hay field.", emoji:"🙌" },
  { n:20, name:"James A. Garfield", short:"Garfield", mnemonic:"Garfield the cat eating twenty lasagnas!", emoji:"🐱" },
  { n:21, name:"Chester A. Arthur", short:"Arthur", mnemonic:"CHEESE-ter King Arthur signing 21 books as an AUTHOR.", emoji:"🧀" },
  { n:22, name:"Grover Cleveland", short:"Cleveland", mnemonic:"A giant CLEAVER cutting corn.", emoji:"🌽" },
  { n:23, name:"Benjamin Harrison", short:"B. Harrison", mnemonic:"Another hairy monkey (Harrison) swinging!", emoji:"🦧" },
  { n:24, name:"Grover Cleveland", short:"Cleveland 2", mnemonic:"The same cleaver comes back for round two!", emoji:"🌽" },
  { n:25, name:"William McKinley", short:"McKinley", mnemonic:"Ronald McDonald with a crown giving 25 burgers.", emoji:"🍔" },
  { n:26, name:"Theodore Roosevelt", short:"T. Roosevelt", mnemonic:"Teddy on a horse wearing a belt of ROSES.", emoji:"🌹" },
  { n:27, name:"William Howard Taft", short:"Taft", mnemonic:"Stuck in sticky TAFFY!", emoji:"🍬" },
  { n:28, name:"Woodrow Wilson", short:"Wilson", mnemonic:"A will (document) coming out of a coffin like a zombie.", emoji:"📜" },
  { n:29, name:"Warren G. Harding", short:"Harding", mnemonic:"A giant metal HARD man standing in the street.", emoji:"🤖" },
  { n:30, name:"Calvin Coolidge", short:"Coolidge", mnemonic:"Standing in a big COOLER keeping cool.", emoji:"🧊" },
  { n:31, name:"Herbert Hoover", short:"Hoover", mnemonic:"A vacuum cleaner HOOVERing up everything.", emoji:"🧹" },
  { n:32, name:"Franklin D. Roosevelt", short:"FDR", mnemonic:"A giant ROOSTER with four roses (32).", emoji:"🐓" },
  { n:33, name:"Harry S. Truman", short:"Truman", mnemonic:"A TRUE man telling the truth with a big star.", emoji:"⭐" },
  { n:34, name:"Dwight D. Eisenhower", short:"Eisenhower", mnemonic:"An EYEball watching everything carefully.", emoji:"👁️" },
  { n:35, name:"John F. Kennedy", short:"Kennedy", mnemonic:"A Ken doll with a candy bar.", emoji:"🍬" },
  { n:36, name:"Lyndon B. Johnson", short:"L.B. Johnson", mnemonic:"John’s son (Johnson) with a big LBJ hat.", emoji:"🧢" },
  { n:37, name:"Richard Nixon", short:"Nixon", mnemonic:"Mixing a big bowl of NIX-on soup.", emoji:"🥣" },
  { n:38, name:"Gerald Ford", short:"Ford", mnemonic:"Driving a shiny FORD car across a river.", emoji:"🚗" },
  { n:39, name:"Jimmy Carter", short:"Carter", mnemonic:"A CART full of peanuts rolling by.", emoji:"🥜" },
  { n:40, name:"Ronald Reagan", short:"Reagan", mnemonic:"A ray-gun (Reagan) shooting stars.", emoji:"🔫" },
  { n:41, name:"George H. W. Bush", short:"H.W. Bush", mnemonic:"A bush with a big H.W. monogram.", emoji:"🌳" },
  { n:42, name:"Bill Clinton", short:"Clinton", mnemonic:"A giant bill (dollar) climbing a mountain.", emoji:"💵" },
  { n:43, name:"George W. Bush", short:"W. Bush", mnemonic:"Another bush, this one with a big W.", emoji:"🌲" },
  { n:44, name:"Barack Obama", short:"Obama", mnemonic:"A bar of soap (Barack) with an “O” shining.", emoji:"🧼" },
  { n:45, name:"Donald Trump", short:"Trump (1st)", mnemonic:"A golden trumpet blasting a fanfare.", emoji:"🎺" },
  { n:46, name:"Joe Biden", short:"Biden", mnemonic:"A bicycle (Bi-den) with a big 46 flag.", emoji:"🚲" },
  { n:47, name:"Donald Trump", short:"Trump (2nd)", mnemonic:"The golden trumpet returns for an encore!", emoji:"🎺" }
];
