const PRESIDENTS = [
  { n:1, name:"George Washington", short:"Washington", mnemonic:"GEORGE washing a giant TON of laundry! Splash!", emoji:"🧺" },
  { n:2, name:"John Adams", short:"Adams", mnemonic:"JOHN adding huge numbers that keep growing.", emoji:"➕" },
  { n:3, name:"Thomas Jefferson", short:"Jefferson", mnemonic:"THOMAS the chef’s son frying atoms in a pan.", emoji:"👨‍🍳" },
  { n:4, name:"James Madison", short:"Madison", mnemonic:"JAMES and a MAD sun yelling on a grill!", emoji:"☀️" },
  { n:5, name:"James Monroe", short:"Monroe", mnemonic:"JAMES the man ROWing with a giant 5 on the oar.", emoji:"🚣" },
  { n:6, name:"John Quincy Adams", short:"Q. Adams", mnemonic:"JOHN Q’s cue ball among 6 balls, bouncing into a dam.", emoji:"🎱" },
  { n:7, name:"Andrew Jackson", short:"Jackson", mnemonic:"ANDREW jack-in-the-box popping from a pumpkin!", emoji:"🎃" },
  { n:8, name:"Martin Van Buren", short:"Van Buren", mnemonic:"MARTIN’s VAN BURNing inside a freezer. Burrrr!", emoji:"🚐" },
  { n:9, name:"William Henry Harrison", short:"W.H. Harrison", mnemonic:"WILL the hairy monkey with a huge pile of HAIR!", emoji:"🐒" },
  { n:10, name:"John Tyler", short:"Tyler", mnemonic:"JOHN tying TEN knots in a long rope.", emoji:"🧶" },
  { n:11, name:"James K. Polk", short:"Polk", mnemonic:"JAMES poking the yard with sticks that look like 11.", emoji:"🥢" },
  { n:12, name:"Zachary Taylor", short:"Taylor", mnemonic:"ZACH the tailor sewing 12 shiny buttons.", emoji:"🧵" },
  { n:13, name:"Millard Fillmore", short:"Fillmore", mnemonic:"MILLARD filling MORE and more glasses — 13 cups!", emoji:"🥛" },
  { n:14, name:"Franklin Pierce", short:"Pierce", mnemonic:"FRANKLIN’s spear PIERCING right through 14.", emoji:"🗡️" },
  { n:15, name:"James Buchanan", short:"Buchanan", mnemonic:"JAMES firing 15 cannons that shout BOO!", emoji:"💣" },
  { n:16, name:"Abraham Lincoln", short:"Lincoln", mnemonic:"ABE in a tall hat speaking under 16 stars.", emoji:"🎩" },
  { n:17, name:"Andrew Johnson", short:"A. Johnson", mnemonic:"ANDREW, John’s son, stitching a bed of 17 pillows.", emoji:"🧵" },
  { n:18, name:"Ulysses S. Grant", short:"Grant", mnemonic:"ULYSSES the genie GRANTing a wish from the lamp.", emoji:"🧞" },
  { n:19, name:"Rutherford B. Hayes", short:"Hayes", mnemonic:"RUTHERFORD yelling HEY! and high-fiving in the hay.", emoji:"🙌" },
  { n:20, name:"James A. Garfield", short:"Garfield", mnemonic:"JAMES Garfield the cat eating 20 lasagnas!", emoji:"🐱" },
  { n:21, name:"Chester A. Arthur", short:"Arthur", mnemonic:"CHEESE-ter King Arthur signing 21 books as an AUTHOR.", emoji:"🧀" },
  { n:22, name:"Grover Cleveland", short:"Cleveland", mnemonic:"GROVER’s giant CLEAVER chopping corn.", emoji:"🌽" },
  { n:23, name:"Benjamin Harrison", short:"B. Harrison", mnemonic:"Hairy monkey counting 23 Benjamin $100 bills!", emoji:"🦍" },
  { n:24, name:"Grover Cleveland", short:"Cleveland 2", mnemonic:"GROVER’s cleaver comes BACK for round two!", emoji:"🌽" },
  { n:25, name:"William McKinley", short:"McKinley", mnemonic:"WILL the KING at the KINLEY gate with 25 burgers.", emoji:"🍔" },
  { n:26, name:"Theodore Roosevelt", short:"T. Roosevelt", mnemonic:"TEDDY on a horse wearing a belt of 26 ROSES.", emoji:"🌹" },
  { n:27, name:"William Howard Taft", short:"Taft", mnemonic:"WILL stuck in sticky TAFFY pulled into a 27.", emoji:"🍬" },
  { n:28, name:"Woodrow Wilson", short:"Wilson", mnemonic:"WOODROW’s will floating up like a ghost from a box.", emoji:"📜" },
  { n:29, name:"Warren G. Harding", short:"Harding", mnemonic:"WAR-ren the HARD man with a wren and 29 bolts.", emoji:"🤖" },
  { n:30, name:"Calvin Coolidge", short:"Coolidge", mnemonic:"CAL IN a COOLER packed with 30 ice cubes.", emoji:"🧊" },
  { n:31, name:"Herbert Hoover", short:"Hoover", mnemonic:"HERB and BERT the Hoover sucking 31 toys.", emoji:"🧹" },
  { n:32, name:"Franklin D. Roosevelt", short:"FDR", mnemonic:"FRANKLIN’s giant ROOSTER wearing roses.", emoji:"🐓" },
  { n:33, name:"Harry S. Truman", short:"Truman", mnemonic:"HARRY the TRUE man pinning on a shining star.", emoji:"⭐" },
  { n:34, name:"Dwight D. Eisenhower", short:"Eisenhower", mnemonic:"DWIGHT’s giant EYEball watching from a tower.", emoji:"👁️" },
  { n:35, name:"John F. Kennedy", short:"Kennedy", mnemonic:"JOHN the Ken doll holding a candy bar.", emoji:"🍬" },
  { n:36, name:"Lyndon B. Johnson", short:"L.B. Johnson", mnemonic:"LYNDON, John’s son, under a big LBJ hat.", emoji:"🧢" },
  { n:37, name:"Richard Nixon", short:"Nixon", mnemonic:"RICHARD mixing a bubbling pot of NIX-on soup.", emoji:"🥣" },
  { n:38, name:"Gerald Ford", short:"Ford", mnemonic:"GERALD driving a shiny FORD across a river.", emoji:"🚗" },
  { n:39, name:"Jimmy Carter", short:"Carter", mnemonic:"JIMMY pushing a CART stuffed with peanuts.", emoji:"🥜" },
  { n:40, name:"Ronald Reagan", short:"Reagan", mnemonic:"RONALD blasting stars from a ray-gun.", emoji:"🔫" },
  { n:41, name:"George H. W. Bush", short:"H.W. Bush", mnemonic:"GEORGE standing by a bush with a giant H.W.", emoji:"🌳" },
  { n:42, name:"Bill Clinton", short:"Clinton", mnemonic:"BILL the dollar bill hiking up a mountain.", emoji:"💵" },
  { n:43, name:"George W. Bush", short:"W. Bush", mnemonic:"GEORGE by another bush, this one a giant W.", emoji:"🌲" },
  { n:44, name:"Barack Obama", short:"Obama", mnemonic:"BARACK and a glowing bar of soap with an O.", emoji:"🧼" },
  { n:45, name:"Donald Trump", short:"Trump (1st)", mnemonic:"DONALD blasting a golden trumpet fanfare.", emoji:"🎺" },
  { n:46, name:"Joe Biden", short:"Biden", mnemonic:"JOE riding a bicycle with a 46 flag.", emoji:"🚲" },
  { n:47, name:"Donald Trump", short:"Trump (2nd)", mnemonic:"DONALD’s golden trumpet comes back for an encore!", emoji:"🎺" }
];
